services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: selesai-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: selesai-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  mysql:
    image: mysql:8.0
    container_name: selesai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selesai
    ports:
      - "3307:3306"
    networks:
      - laravel_net
    volumes:
      - selesai_mysql:/var/lib/mysql

networks:
  laravel_net:

volumes:
  selesai_mysql:
