services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: selesai-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: selesai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net
  
  scheduler:
   build:
     context: .
     dockerfile: docker/php/Dockerfile
   container_name: selesai-scheduler
   command: php artisan schedule:work
   restart: unless-stopped
   depends_on:
     - app
   networks:
     - laravel_net
   volumes:
     - .:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: selesai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selesai
    ports:
      - "3306:3306"
    networks:
      - laravel_net
    volumes:
      - selesai_mysql:/var/lib/mysql

  node:
    image: node:20
    container_name: selesai-vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run build"
    ports:
      - "5173:5173"
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  selesai_mysql:
